spring:
  application:
    name: learn-spring

  datasource:
    url: jdbc:postgresql://localhost:5432/learn-spring
    username: postgres
    password: senha

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
